export const CAGIBI_SHORT_PREFIX = '卡吉比';
export const COMPRESSED_PREFIX_LENGTH = 4;
export const COMPRESSED_STORAGE_BINARY_STRING__PREFIX = `STBS${CAGIBI_SHORT_PREFIX}`;
export const COMPRESSED_JSON_PREFIX = `JSON${CAGIBI_SHORT_PREFIX}`;